"""changed column name 'owner_id' to 'user_id'

Revision ID: ca84f2b40d71
Revises: da4b67f8e14c
Create Date: 2026-01-10 01:15:47.743314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca84f2b40d71'
down_revision: Union[str, Sequence[str], None] = 'da4b67f8e14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the column as NULLABLE first
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True, comment='Unique identifier for the user of the comment'))
    
    # 2. Copy data from 'owner_id' to 'user_id' (if renaming)
    # Or set a default value for existing rows
    op.execute("UPDATE comment SET user_id = owner_id") 
    
    # 3. Now that every row has a value, make it NOT NULL
    op.alter_column('comment', 'user_id', nullable=False)
    
    # Clean up the old column and indexes
    op.drop_index(op.f('ix_comment_owner_id'), table_name='comment')
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.drop_column('comment', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the old 'owner_id' column back as nullable
    op.add_column('comment', sa.Column('owner_id', sa.Integer(), nullable=True))
    
    # 2. Restore the data: Copy values from 'user_id' back to 'owner_id'
    op.execute("UPDATE comment SET owner_id = user_id")
    
    # 3. Restore the old index
    op.create_index(op.f('ix_comment_owner_id'), 'comment', ['owner_id'], unique=False)
    
    # 4. Remove the 'user_id' column and its index
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###