"""First migration

Revision ID: da4b67f8e14c
Revises: 
Create Date: 2026-01-08 23:16:50.294058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4b67f8e14c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the comment (Auto-incrementing PK).'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='Unique identifier for the owner/user/creator of the comment'),
    sa.Column('post_id', sa.Integer(), nullable=False, comment='Unique identifier for the post where the comment is written'),
    sa.Column('text', sa.String(length=256), nullable=True, comment='string of 256 lenght max.'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of when the comment was created.'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_index(op.f('ix_comment_id'), 'comment', ['id'], unique=True)
    op.create_index(op.f('ix_comment_owner_id'), 'comment', ['owner_id'], unique=False)
    op.create_index(op.f('ix_comment_post_id'), 'comment', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_post_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_owner_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_id'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
